# Site settings
title: Emilie
email: edeltil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/freelance" # the subpath of your site, e.g. /blog/
url: "http://emilie-deltil.com" # the base hostname & protocol for your site
twitter_username: EmilieDeltil
github_username:  edeltil
exclude: [bower.json, GruntFile.js, package.json, node_modules, Rakefile]

# Build settings
markdown: kramdown

#google_analytics: UA-68384670-1

sitemap:
    file: "/sitemap.xml"
    include_posts:
        - "/index.html"

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
#analytics:
#  provider: google
#  google:
#      tracking_id: UA-68384670-1
